"use server";

import { prisma } from "@/lib/prisma";
import { randomBytes } from "crypto";
import { sendConfirmationEmail } from "@/lib/utils/email";

export type ResendResponse = {
    success?: boolean;
    error?: string;
    alreadyVerified?: boolean;
};

export async function resendTokenAction(email: string): Promise<ResendResponse> {
    if (!email) {
        return { error: "Email is required." };
    }

    try {
        const user = await prisma.user.findUnique({
            where: { email }
        });

        if (!user) {
            // Return success anyway to prevent email enumeration attacks
            return { success: true };
        }

        if (user.emailVerifid) {
            return { alreadyVerified: true, error: "Email is already verified." };
        }

        // Rate Limiting: Check if the last token was generated less than 60 seconds ago.
        // We calculate when it was generated by subtracting 24 hours from the expiry.
        if (user.emailTokenExpiry) {
            const tokenGeneratedAt = user.emailTokenExpiry.getTime() - 24 * 60 * 60 * 1000;
            const timeSinceLastToken = Date.now() - tokenGeneratedAt;

            if (timeSinceLastToken < 60000) { // 60 seconds
                return { error: "Please wait 60 seconds before requesting a new email." };
            }
        }

        // Generate a new cryptographically secure token
        const newEmailToken = randomBytes(32).toString('hex');
        const newEmailTokenExpiry = new Date(Date.now() + 24 * 60 * 60 * 1000);

        await prisma.user.update({
            where: { id: user.id },
            data: {
                emailToken: newEmailToken,
                emailTokenExpiry: newEmailTokenExpiry,
            }
        });

        // Send the fresh email
        const validateEmailLink = `${process.env.NEXT_PUBLIC_URL}/registration/confirm?token=${newEmailToken}`;
        const { error } = await sendConfirmationEmail(
            email,
            validateEmailLink,
            email.split('@')[0]
        );

        if (error) {
            console.error("Failed to resend confirmation email:", error);
            return { error: "Failed to send the email. Please try again later." };
        }

        return { success: true };

    } catch (error) {
        console.error("Resend token error:", error);
        return { error: "An unexpected error occurred." };
    }
}
